package com.jeff.fx.common;

public enum Instrument 
{
    AUDJPY, AUDNZD, AUDUSD, EURAUD, EURCHF, 
    EURGBP, EURJPY, EURUSD, GBPCHF, GBPJPY, 
    GBPUSD, NZDUSD, USDCAD, USDCHF, USDJPY,
    
    EURCAD, EURDKK, CADJPY, CHFJPY, EURHKD, 
    EURNOK, EURSEK, USDDKK, USDHKD, USDMXN, 
    USDNOK, USDSEK, USDSGD, USDTRY,
    
    XAUUSD, XAGUSD;
}