/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExecutorParametersView.java
 *
 * Created on 12/08/2010, 7:42:42 PM
 */

package com.jeff.fx.backtest.strategy.optimiser;

import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTextField;

import org.jdesktop.swingx.JXLabel;

import com.jeff.fx.gui.PIntComboBox;

/**
 *
 * @author jeff
 */
@SuppressWarnings("serial")
public class ExecutorParametersView extends javax.swing.JPanel {

    /** Creates new form ExecutorParametersView */
    public ExecutorParametersView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlControls = new javax.swing.JPanel();
        lblThreadCount = new javax.swing.JLabel();
        cboThreadCount = new PIntComboBox("multiThreadExecutor.threads", 1, 2, 3, 4, 6, 8, 12, 16, 20, 24, 32, 48, 64, 128);
        cboBlockSize = new PIntComboBox("multiThreadExecutor.blockSize", 1, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000);
        lblBalanceThreshold = new javax.swing.JLabel();
        txtBalanceThreshold = new javax.swing.JTextField();
        lblWinThreshold = new javax.swing.JLabel();
        spinWinThreshold = new javax.swing.JSpinner();
        filler = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlControls.setLayout(new java.awt.GridLayout(4, 2));

        lblThreadCount.setText("Executor Threads");
        pnlControls.add(lblThreadCount);
        pnlControls.add(cboThreadCount);

        pnlControls.add(new JXLabel("Job Block Size"));
        pnlControls.add(cboBlockSize);

        lblBalanceThreshold.setText("Balance Threshold");
        pnlControls.add(lblBalanceThreshold);
        txtBalanceThreshold.setText("100");
        pnlControls.add(txtBalanceThreshold);

        lblWinThreshold.setText("Win% Threshold");
        pnlControls.add(lblWinThreshold);
        spinWinThreshold.setValue(50);
        pnlControls.add(spinWinThreshold);

        add(pnlControls, java.awt.BorderLayout.PAGE_START);

        filler.setLayout(new java.awt.BorderLayout());
        add(filler, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox getCboThreadCount() {
        return cboThreadCount;
    }

    public JComboBox getCboBlockSize() {
        return cboBlockSize;
    }

    public JSpinner getSpinWinThreshold() {
        return spinWinThreshold;
    }

    public JTextField getTxtBalanceThreshold() {
        return txtBalanceThreshold;
    }//GEN-LAST:event_txtBalanceThresholdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboThreadCount;
    private javax.swing.JComboBox cboBlockSize;
    private javax.swing.JPanel filler;
    private javax.swing.JLabel lblBalanceThreshold;
    private javax.swing.JLabel lblThreadCount;
    private javax.swing.JLabel lblWinThreshold;
    private javax.swing.JPanel pnlControls;
    private javax.swing.JSpinner spinWinThreshold;
    private javax.swing.JTextField txtBalanceThreshold;
    // End of variables declaration//GEN-END:variables

}
