/*
 * Created on 11/08/2010, 5:26:42 PM
 */

package com.jeff.fx.backtest.dataviewer;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

import org.jdesktop.swingx.JXTable;

/**
 *
 * @author jeff
 */
public class CandleDataView extends javax.swing.JPanel {

    /** Creates new form NewJPanel */
    public CandleDataView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        table = new JXTable();
        pnlActions = new javax.swing.JPanel();
        btnPrevWeek = new javax.swing.JButton();
        btnNextWeek = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPane.setViewportView(table);

        add(scrollPane, java.awt.BorderLayout.CENTER);

        btnPrevWeek.setText("< Prev");
        pnlActions.add(btnPrevWeek);

        btnNextWeek.setText("Next >");
        pnlActions.add(btnNextWeek);

        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });
        btnDone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnDoneFocusGained(evt);
            }
        });
        pnlActions.add(btnDone);

        add(pnlActions, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnDoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnDoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoneFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnNextWeek;
    private javax.swing.JButton btnPrevWeek;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JScrollPane scrollPane;
    private JXTable table;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnDone() {
        return btnDone;
    }

    public void setBtnDone(JButton btnDone) {
        this.btnDone = btnDone;
    }

    public JButton getBtnNextWeek() {
        return btnNextWeek;
    }

    public void setBtnNextWeek(JButton btnNextWeek) {
        this.btnNextWeek = btnNextWeek;
    }

    public JButton getBtnPrevWeek() {
        return btnPrevWeek;
    }

    public void setBtnPrevWeek(JButton btnPrevWeek) {
        this.btnPrevWeek = btnPrevWeek;
    }

    public JPanel getPnlActions() {
        return pnlActions;
    }

    public void setPnlActions(JPanel pnlActions) {
        this.pnlActions = pnlActions;
    }

    public JScrollPane getScrollPane() {
        return scrollPane;
    }

    public void setScrollPane(JScrollPane scrollPane) {
        this.scrollPane = scrollPane;
    }

    public JXTable getTable() {
        return table;
    }

    public void setTable(JXTable table) {
        this.table = table;
    }

}
