package com.siebentag.fx.source.gain;

public enum GainInstruments 
{
	AUD_CAD, AUD_CHF, AUD_JPY, AUD_NZD, AUD_USD, 
	EUR_AUD, EUR_CHF, EUR_GBP, EUR_JPY,	EUR_USD, 
	GBP_AUD, GBP_CHF, GBP_JPY, GBP_USD, NZD_USD, 
	USD_CAD, USD_CHF 
	
	/*
	SGD_JPY, EUR_CAD, EUR_DKK, CAD_CHF, CAD_JPY, 
	CHF_JPY, GBP_CAD, GBP_NZD, USD_HKD, USD_JPY, 
	USD_NOK, USD_SEK, USD_SGD, EUR_NOK, EUR_NZD, 
	EUR_SEK, NZD_CAD, NZD_CHF, NZD_JPY, USD_DKK
	*/ 
}	
