//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.01 at 02:50:57 PM GMT 
//


package com.siebentag.cj.model;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for Attributes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Attributes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objectId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="batting" type="{http://www.siebentag.com/steamboat/xsd}BattingAttributes"/>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Attributes", propOrder = {
    "objectId",
    "batting",
    "comment"
})
@Entity(name = "com.siebentag.cj.model.Attributes")
@Table(name = "t_attributes")
@Inheritance(strategy = InheritanceType.JOINED)
public class Attributes
    implements Equals, HashCode
{

    protected long objectId;
    @XmlElement(required = true)
    protected com.siebentag.cj.model.BattingAttributes batting;
    @XmlElement(required = true)
    protected String comment;

    /**
     * Gets the value of the objectId property.
     * 
     */
    @Id
    @Column(name = "object_id", scale = 0)
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     */
    public void setObjectId(long value) {
        this.objectId = value;
    }

    @Transient
    public boolean isSetObjectId() {
        return true;
    }

    /**
     * Gets the value of the batting property.
     * 
     * @return
     *     possible object is
     *     {@link com.siebentag.cj.model.BattingAttributes }
     *     
     */
    @ManyToOne(targetEntity = com.siebentag.cj.model.BattingAttributes.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "attributes_batting_id")
    public com.siebentag.cj.model.BattingAttributes getBatting() {
        return batting;
    }

    /**
     * Sets the value of the batting property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.siebentag.cj.model.BattingAttributes }
     *     
     */
    public void setBatting(com.siebentag.cj.model.BattingAttributes value) {
        this.batting = value;
    }

    @Transient
    public boolean isSetBatting() {
        return (this.batting!= null);
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "comment")
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    @Transient
    public boolean isSetComment() {
        return (this.comment!= null);
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof Attributes)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final Attributes that = ((Attributes) object);
        equalsBuilder.append(this.getObjectId(), that.getObjectId());
        equalsBuilder.append(this.getBatting(), that.getBatting());
        equalsBuilder.append(this.getComment(), that.getComment());
    }

    public boolean equals(Object object) {
        if (!(object instanceof Attributes)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getObjectId());
        hashCodeBuilder.append(this.getBatting());
        hashCodeBuilder.append(this.getComment());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
