//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.01 at 02:50:57 PM GMT 
//


package com.siebentag.cj.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WicketType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WicketType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Bowled"/>
 *     &lt;enumeration value="Caught"/>
 *     &lt;enumeration value="CaughtBehind"/>
 *     &lt;enumeration value="CaughtAndBowled"/>
 *     &lt;enumeration value="RunOut"/>
 *     &lt;enumeration value="LBW"/>
 *     &lt;enumeration value="Mankad"/>
 *     &lt;enumeration value="Stumped"/>
 *     &lt;enumeration value="HitWicket"/>
 *     &lt;enumeration value="NotOut"/>
 *     &lt;enumeration value="Retired"/>
 *     &lt;enumeration value="RetiredHurt"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "WicketType")
@XmlEnum
public enum WicketType {

    @XmlEnumValue("Bowled")
    BOWLED("Bowled"),
    @XmlEnumValue("Caught")
    CAUGHT("Caught"),
    @XmlEnumValue("CaughtBehind")
    CAUGHT_BEHIND("CaughtBehind"),
    @XmlEnumValue("CaughtAndBowled")
    CAUGHT_AND_BOWLED("CaughtAndBowled"),
    @XmlEnumValue("RunOut")
    RUN_OUT("RunOut"),
    LBW("LBW"),
    @XmlEnumValue("Mankad")
    MANKAD("Mankad"),
    @XmlEnumValue("Stumped")
    STUMPED("Stumped"),
    @XmlEnumValue("HitWicket")
    HIT_WICKET("HitWicket"),
    @XmlEnumValue("NotOut")
    NOT_OUT("NotOut"),
    @XmlEnumValue("Retired")
    RETIRED("Retired"),
    @XmlEnumValue("RetiredHurt")
    RETIRED_HURT("RetiredHurt");
    private final String value;

    WicketType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WicketType fromValue(String v) {
        for (WicketType c: WicketType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
