//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.01 at 02:50:57 PM GMT 
//


package com.siebentag.cj.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for BatsmanInningsCollection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BatsmanInningsCollection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objectId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="innings" type="{http://www.siebentag.com/steamboat/xsd}BatsmanInnings" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="partnerships" type="{http://www.siebentag.com/steamboat/xsd}Partnership" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatsmanInningsCollection", propOrder = {
    "objectId",
    "innings",
    "partnerships",
    "comment"
})
@Entity(name = "com.siebentag.cj.model.BatsmanInningsCollection")
@Table(name = "t_batsman_innings_collection")
@Inheritance(strategy = InheritanceType.JOINED)
public class BatsmanInningsCollection
    implements Equals, HashCode
{

    protected long objectId;
    protected List<com.siebentag.cj.model.BatsmanInnings> innings;
    protected List<com.siebentag.cj.model.Partnership> partnerships;
    @XmlElement(required = true)
    protected String comment;

    /**
     * Gets the value of the objectId property.
     * 
     */
    @Id
    @Column(name = "object_id", scale = 0)
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     */
    public void setObjectId(long value) {
        this.objectId = value;
    }

    @Transient
    public boolean isSetObjectId() {
        return true;
    }

    /**
     * Gets the value of the innings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the innings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInnings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.siebentag.cj.model.BatsmanInnings }
     * 
     * 
     */
    @OneToMany(targetEntity = com.siebentag.cj.model.BatsmanInnings.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "batsman_innings_collection_i_0")
    public List<com.siebentag.cj.model.BatsmanInnings> getInnings() {
        if (innings == null) {
            innings = new ArrayList<com.siebentag.cj.model.BatsmanInnings>();
        }
        return this.innings;
    }

    /**
     * 
     * 
     */
    public void setInnings(List<com.siebentag.cj.model.BatsmanInnings> innings) {
        this.innings = innings;
    }

    @Transient
    public boolean isSetInnings() {
        return ((this.innings!= null)&&(!this.innings.isEmpty()));
    }

    public void unsetInnings() {
        this.innings = null;
    }

    /**
     * Gets the value of the partnerships property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partnerships property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartnerships().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.siebentag.cj.model.Partnership }
     * 
     * 
     */
    @OneToMany(targetEntity = com.siebentag.cj.model.Partnership.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "batsman_innings_collection_p_0")
    public List<com.siebentag.cj.model.Partnership> getPartnerships() {
        if (partnerships == null) {
            partnerships = new ArrayList<com.siebentag.cj.model.Partnership>();
        }
        return this.partnerships;
    }

    /**
     * 
     * 
     */
    public void setPartnerships(List<com.siebentag.cj.model.Partnership> partnerships) {
        this.partnerships = partnerships;
    }

    @Transient
    public boolean isSetPartnerships() {
        return ((this.partnerships!= null)&&(!this.partnerships.isEmpty()));
    }

    public void unsetPartnerships() {
        this.partnerships = null;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "comment")
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    @Transient
    public boolean isSetComment() {
        return (this.comment!= null);
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof BatsmanInningsCollection)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final BatsmanInningsCollection that = ((BatsmanInningsCollection) object);
        equalsBuilder.append(this.getObjectId(), that.getObjectId());
        equalsBuilder.append(this.getInnings(), that.getInnings());
        equalsBuilder.append(this.getPartnerships(), that.getPartnerships());
        equalsBuilder.append(this.getComment(), that.getComment());
    }

    public boolean equals(Object object) {
        if (!(object instanceof BatsmanInningsCollection)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getObjectId());
        hashCodeBuilder.append(this.getInnings());
        hashCodeBuilder.append(this.getPartnerships());
        hashCodeBuilder.append(this.getComment());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
