//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.01 at 02:50:57 PM GMT 
//


package com.siebentag.cj.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for Country complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Country">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="primaryColour" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="secondaryColour" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tertiaryColour" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Country", propOrder = {
    "code",
    "name",
    "flag",
    "primaryColour",
    "secondaryColour",
    "tertiaryColour"
})
@Entity(name = "com.siebentag.cj.model.Country")
@Table(name = "t_country")
@Inheritance(strategy = InheritanceType.JOINED)
public class Country
    implements Equals, HashCode
{

    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String flag;
    @XmlElement(required = true)
    protected String primaryColour;
    @XmlElement(required = true)
    protected String secondaryColour;
    @XmlElement(required = true)
    protected String tertiaryColour;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Id
    @Column(name = "code")
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    @Transient
    public boolean isSetCode() {
        return (this.code!= null);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "name")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    @Transient
    public boolean isSetName() {
        return (this.name!= null);
    }

    /**
     * Gets the value of the flag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "flag")
    public String getFlag() {
        return flag;
    }

    /**
     * Sets the value of the flag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlag(String value) {
        this.flag = value;
    }

    @Transient
    public boolean isSetFlag() {
        return (this.flag!= null);
    }

    /**
     * Gets the value of the primaryColour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "primary_colour")
    public String getPrimaryColour() {
        return primaryColour;
    }

    /**
     * Sets the value of the primaryColour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryColour(String value) {
        this.primaryColour = value;
    }

    @Transient
    public boolean isSetPrimaryColour() {
        return (this.primaryColour!= null);
    }

    /**
     * Gets the value of the secondaryColour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "secondary_colour")
    public String getSecondaryColour() {
        return secondaryColour;
    }

    /**
     * Sets the value of the secondaryColour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryColour(String value) {
        this.secondaryColour = value;
    }

    @Transient
    public boolean isSetSecondaryColour() {
        return (this.secondaryColour!= null);
    }

    /**
     * Gets the value of the tertiaryColour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "tertiary_colour")
    public String getTertiaryColour() {
        return tertiaryColour;
    }

    /**
     * Sets the value of the tertiaryColour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTertiaryColour(String value) {
        this.tertiaryColour = value;
    }

    @Transient
    public boolean isSetTertiaryColour() {
        return (this.tertiaryColour!= null);
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof Country)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final Country that = ((Country) object);
        equalsBuilder.append(this.getCode(), that.getCode());
        equalsBuilder.append(this.getName(), that.getName());
        equalsBuilder.append(this.getFlag(), that.getFlag());
        equalsBuilder.append(this.getPrimaryColour(), that.getPrimaryColour());
        equalsBuilder.append(this.getSecondaryColour(), that.getSecondaryColour());
        equalsBuilder.append(this.getTertiaryColour(), that.getTertiaryColour());
    }

    public boolean equals(Object object) {
        if (!(object instanceof Country)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getCode());
        hashCodeBuilder.append(this.getName());
        hashCodeBuilder.append(this.getFlag());
        hashCodeBuilder.append(this.getPrimaryColour());
        hashCodeBuilder.append(this.getSecondaryColour());
        hashCodeBuilder.append(this.getTertiaryColour());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
