//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.01 at 02:50:57 PM GMT 
//


package com.siebentag.cj.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDateTime;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for Match complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Match">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objectId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="roundNumber" type="{http://www.siebentag.com/steamboat/xsd}Ordinal"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="homeTeam" type="{http://www.siebentag.com/steamboat/xsd}Team"/>
 *         &lt;element name="awayTeam" type="{http://www.siebentag.com/steamboat/xsd}Team"/>
 *         &lt;element name="innings" type="{http://www.siebentag.com/steamboat/xsd}MatchInnings" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Match", propOrder = {
    "objectId",
    "roundNumber",
    "description",
    "startDate",
    "homeTeam",
    "awayTeam",
    "innings"
})
@Entity(name = "com.siebentag.cj.model.Match")
@Table(name = "t_match")
@Inheritance(strategy = InheritanceType.JOINED)
public class Match
    implements Equals, HashCode
{

    protected long objectId;
    protected int roundNumber;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlElement(required = true)
    protected com.siebentag.cj.model.Team homeTeam;
    @XmlElement(required = true)
    protected com.siebentag.cj.model.Team awayTeam;
    protected List<com.siebentag.cj.model.MatchInnings> innings;

    /**
     * Gets the value of the objectId property.
     * 
     */
    @Id
    @Column(name = "object_id", scale = 0)
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     */
    public void setObjectId(long value) {
        this.objectId = value;
    }

    @Transient
    public boolean isSetObjectId() {
        return true;
    }

    /**
     * Gets the value of the roundNumber property.
     * 
     */
    @Basic
    @Column(name = "round_number", scale = 0)
    public int getRoundNumber() {
        return roundNumber;
    }

    /**
     * Sets the value of the roundNumber property.
     * 
     */
    public void setRoundNumber(int value) {
        this.roundNumber = value;
    }

    @Transient
    public boolean isSetRoundNumber() {
        return true;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "description")
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    @Transient
    public boolean isSetDescription() {
        return (this.description!= null);
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    @Transient
    public boolean isSetStartDate() {
        return (this.startDate!= null);
    }

    /**
     * Gets the value of the homeTeam property.
     * 
     * @return
     *     possible object is
     *     {@link com.siebentag.cj.model.Team }
     *     
     */
    @ManyToOne(targetEntity = com.siebentag.cj.model.Team.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "match_home_team_id")
    public com.siebentag.cj.model.Team getHomeTeam() {
        return homeTeam;
    }

    /**
     * Sets the value of the homeTeam property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.siebentag.cj.model.Team }
     *     
     */
    public void setHomeTeam(com.siebentag.cj.model.Team value) {
        this.homeTeam = value;
    }

    @Transient
    public boolean isSetHomeTeam() {
        return (this.homeTeam!= null);
    }

    /**
     * Gets the value of the awayTeam property.
     * 
     * @return
     *     possible object is
     *     {@link com.siebentag.cj.model.Team }
     *     
     */
    @ManyToOne(targetEntity = com.siebentag.cj.model.Team.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "match_away_team_id")
    public com.siebentag.cj.model.Team getAwayTeam() {
        return awayTeam;
    }

    /**
     * Sets the value of the awayTeam property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.siebentag.cj.model.Team }
     *     
     */
    public void setAwayTeam(com.siebentag.cj.model.Team value) {
        this.awayTeam = value;
    }

    @Transient
    public boolean isSetAwayTeam() {
        return (this.awayTeam!= null);
    }

    /**
     * Gets the value of the innings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the innings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInnings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.siebentag.cj.model.MatchInnings }
     * 
     * 
     */
    @OneToMany(targetEntity = com.siebentag.cj.model.MatchInnings.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "match_innings_id")
    public List<com.siebentag.cj.model.MatchInnings> getInnings() {
        if (innings == null) {
            innings = new ArrayList<com.siebentag.cj.model.MatchInnings>();
        }
        return this.innings;
    }

    /**
     * 
     * 
     */
    public void setInnings(List<com.siebentag.cj.model.MatchInnings> innings) {
        this.innings = innings;
    }

    @Transient
    public boolean isSetInnings() {
        return ((this.innings!= null)&&(!this.innings.isEmpty()));
    }

    public void unsetInnings() {
        this.innings = null;
    }

    @Basic
    @Column(name = "start_date_item")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getStartDateItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDateTime.class, this.getStartDate());
    }

    public void setStartDateItem(Date target) {
        setStartDate(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDateTime.class, target));
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof Match)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final Match that = ((Match) object);
        equalsBuilder.append(this.getObjectId(), that.getObjectId());
        equalsBuilder.append(this.getRoundNumber(), that.getRoundNumber());
        equalsBuilder.append(this.getDescription(), that.getDescription());
        equalsBuilder.append(this.getStartDate(), that.getStartDate());
        equalsBuilder.append(this.getHomeTeam(), that.getHomeTeam());
        equalsBuilder.append(this.getAwayTeam(), that.getAwayTeam());
        equalsBuilder.append(this.getInnings(), that.getInnings());
    }

    public boolean equals(Object object) {
        if (!(object instanceof Match)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getObjectId());
        hashCodeBuilder.append(this.getRoundNumber());
        hashCodeBuilder.append(this.getDescription());
        hashCodeBuilder.append(this.getStartDate());
        hashCodeBuilder.append(this.getHomeTeam());
        hashCodeBuilder.append(this.getAwayTeam());
        hashCodeBuilder.append(this.getInnings());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
