//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.01 at 02:50:57 PM GMT 
//


package com.siebentag.cj.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for Partnership complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Partnership">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objectId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ordinal" type="{http://www.siebentag.com/steamboat/xsd}Ordinal"/>
 *         &lt;element name="balls" type="{http://www.siebentag.com/steamboat/xsd}Ball" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Partnership", propOrder = {
    "objectId",
    "ordinal",
    "balls"
})
@Entity(name = "com.siebentag.cj.model.Partnership")
@Table(name = "t_partnership")
@Inheritance(strategy = InheritanceType.JOINED)
public class Partnership
    implements Equals, HashCode
{

    protected long objectId;
    protected int ordinal;
    protected List<com.siebentag.cj.model.Ball> balls;

    /**
     * Gets the value of the objectId property.
     * 
     */
    @Id
    @Column(name = "object_id", scale = 0)
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     */
    public void setObjectId(long value) {
        this.objectId = value;
    }

    @Transient
    public boolean isSetObjectId() {
        return true;
    }

    /**
     * Gets the value of the ordinal property.
     * 
     */
    @Basic
    @Column(name = "ordinal", scale = 0)
    public int getOrdinal() {
        return ordinal;
    }

    /**
     * Sets the value of the ordinal property.
     * 
     */
    public void setOrdinal(int value) {
        this.ordinal = value;
    }

    @Transient
    public boolean isSetOrdinal() {
        return true;
    }

    /**
     * Gets the value of the balls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the balls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBalls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.siebentag.cj.model.Ball }
     * 
     * 
     */
    @OneToMany(targetEntity = com.siebentag.cj.model.Ball.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "partnership_balls_id")
    public List<com.siebentag.cj.model.Ball> getBalls() {
        if (balls == null) {
            balls = new ArrayList<com.siebentag.cj.model.Ball>();
        }
        return this.balls;
    }

    /**
     * 
     * 
     */
    public void setBalls(List<com.siebentag.cj.model.Ball> balls) {
        this.balls = balls;
    }

    @Transient
    public boolean isSetBalls() {
        return ((this.balls!= null)&&(!this.balls.isEmpty()));
    }

    public void unsetBalls() {
        this.balls = null;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof Partnership)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final Partnership that = ((Partnership) object);
        equalsBuilder.append(this.getObjectId(), that.getObjectId());
        equalsBuilder.append(this.getOrdinal(), that.getOrdinal());
        equalsBuilder.append(this.getBalls(), that.getBalls());
    }

    public boolean equals(Object object) {
        if (!(object instanceof Partnership)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getObjectId());
        hashCodeBuilder.append(this.getOrdinal());
        hashCodeBuilder.append(this.getBalls());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
