//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.01 at 02:50:57 PM GMT 
//


package com.siebentag.cj.model;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDate;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for Player complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Player">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="username" type="{http://www.siebentag.com/steamboat/xsd}Username"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dob" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="battingStyle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bowlingStyle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pictureUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attributes" type="{http://www.siebentag.com/steamboat/xsd}Attributes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Player", propOrder = {
    "username",
    "firstName",
    "surname",
    "displayName",
    "origin",
    "dob",
    "role",
    "battingStyle",
    "bowlingStyle",
    "height",
    "pictureUrl",
    "attributes"
})
@Entity(name = "com.siebentag.cj.model.Player")
@Table(name = "t_player")
@Inheritance(strategy = InheritanceType.JOINED)
public class Player
    implements Equals, HashCode
{

    @XmlElement(required = true)
    protected String username;
    @XmlElement(required = true)
    protected String firstName;
    @XmlElement(required = true)
    protected String surname;
    @XmlElement(required = true)
    protected String displayName;
    @XmlElement(required = true)
    protected String origin;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dob;
    @XmlElement(required = true)
    protected String role;
    @XmlElement(required = true)
    protected String battingStyle;
    @XmlElement(required = true)
    protected String bowlingStyle;
    @XmlElement(required = true)
    protected String height;
    @XmlElement(required = true)
    protected String pictureUrl;
    @XmlElement(required = true)
    protected com.siebentag.cj.model.Attributes attributes;

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Id
    @Column(name = "username", length = 32)
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    @Transient
    public boolean isSetUsername() {
        return (this.username!= null);
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "first_name")
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    @Transient
    public boolean isSetFirstName() {
        return (this.firstName!= null);
    }

    /**
     * Gets the value of the surname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "surname")
    public String getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    @Transient
    public boolean isSetSurname() {
        return (this.surname!= null);
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "display_name")
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    @Transient
    public boolean isSetDisplayName() {
        return (this.displayName!= null);
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "origin")
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    @Transient
    public boolean isSetOrigin() {
        return (this.origin!= null);
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getDob() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDob(XMLGregorianCalendar value) {
        this.dob = value;
    }

    @Transient
    public boolean isSetDob() {
        return (this.dob!= null);
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "role")
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    @Transient
    public boolean isSetRole() {
        return (this.role!= null);
    }

    /**
     * Gets the value of the battingStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "batting_style")
    public String getBattingStyle() {
        return battingStyle;
    }

    /**
     * Sets the value of the battingStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBattingStyle(String value) {
        this.battingStyle = value;
    }

    @Transient
    public boolean isSetBattingStyle() {
        return (this.battingStyle!= null);
    }

    /**
     * Gets the value of the bowlingStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "bowling_style")
    public String getBowlingStyle() {
        return bowlingStyle;
    }

    /**
     * Sets the value of the bowlingStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBowlingStyle(String value) {
        this.bowlingStyle = value;
    }

    @Transient
    public boolean isSetBowlingStyle() {
        return (this.bowlingStyle!= null);
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "height")
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    @Transient
    public boolean isSetHeight() {
        return (this.height!= null);
    }

    /**
     * Gets the value of the pictureUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "picture_url")
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * Sets the value of the pictureUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPictureUrl(String value) {
        this.pictureUrl = value;
    }

    @Transient
    public boolean isSetPictureUrl() {
        return (this.pictureUrl!= null);
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link com.siebentag.cj.model.Attributes }
     *     
     */
    @ManyToOne(targetEntity = com.siebentag.cj.model.Attributes.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "player_attributes_id")
    public com.siebentag.cj.model.Attributes getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.siebentag.cj.model.Attributes }
     *     
     */
    public void setAttributes(com.siebentag.cj.model.Attributes value) {
        this.attributes = value;
    }

    @Transient
    public boolean isSetAttributes() {
        return (this.attributes!= null);
    }

    @Basic
    @Column(name = "dob_item")
    @Temporal(TemporalType.DATE)
    public Date getDobItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDate.class, this.getDob());
    }

    public void setDobItem(Date target) {
        setDob(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDate.class, target));
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof Player)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final Player that = ((Player) object);
        equalsBuilder.append(this.getUsername(), that.getUsername());
        equalsBuilder.append(this.getFirstName(), that.getFirstName());
        equalsBuilder.append(this.getSurname(), that.getSurname());
        equalsBuilder.append(this.getDisplayName(), that.getDisplayName());
        equalsBuilder.append(this.getOrigin(), that.getOrigin());
        equalsBuilder.append(this.getDob(), that.getDob());
        equalsBuilder.append(this.getRole(), that.getRole());
        equalsBuilder.append(this.getBattingStyle(), that.getBattingStyle());
        equalsBuilder.append(this.getBowlingStyle(), that.getBowlingStyle());
        equalsBuilder.append(this.getHeight(), that.getHeight());
        equalsBuilder.append(this.getPictureUrl(), that.getPictureUrl());
        equalsBuilder.append(this.getAttributes(), that.getAttributes());
    }

    public boolean equals(Object object) {
        if (!(object instanceof Player)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getUsername());
        hashCodeBuilder.append(this.getFirstName());
        hashCodeBuilder.append(this.getSurname());
        hashCodeBuilder.append(this.getDisplayName());
        hashCodeBuilder.append(this.getOrigin());
        hashCodeBuilder.append(this.getDob());
        hashCodeBuilder.append(this.getRole());
        hashCodeBuilder.append(this.getBattingStyle());
        hashCodeBuilder.append(this.getBowlingStyle());
        hashCodeBuilder.append(this.getHeight());
        hashCodeBuilder.append(this.getPictureUrl());
        hashCodeBuilder.append(this.getAttributes());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
