//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.01 at 02:50:57 PM GMT 
//


package com.siebentag.cj.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for BattingAttributes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BattingAttributes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objectId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ability" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="timing" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="power" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BattingAttributes", propOrder = {
    "objectId",
    "ability",
    "timing",
    "power"
})
@Entity(name = "com.siebentag.cj.model.BattingAttributes")
@Table(name = "t_batting_attributes")
@Inheritance(strategy = InheritanceType.JOINED)
public class BattingAttributes
    implements Equals, HashCode
{

    protected long objectId;
    protected int ability;
    protected int timing;
    protected int power;

    /**
     * Gets the value of the objectId property.
     * 
     */
    @Id
    @Column(name = "object_id", scale = 0)
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     */
    public void setObjectId(long value) {
        this.objectId = value;
    }

    @Transient
    public boolean isSetObjectId() {
        return true;
    }

    /**
     * Gets the value of the ability property.
     * 
     */
    @Basic
    @Column(name = "ability", scale = 0)
    public int getAbility() {
        return ability;
    }

    /**
     * Sets the value of the ability property.
     * 
     */
    public void setAbility(int value) {
        this.ability = value;
    }

    @Transient
    public boolean isSetAbility() {
        return true;
    }

    /**
     * Gets the value of the timing property.
     * 
     */
    @Basic
    @Column(name = "timing", scale = 0)
    public int getTiming() {
        return timing;
    }

    /**
     * Sets the value of the timing property.
     * 
     */
    public void setTiming(int value) {
        this.timing = value;
    }

    @Transient
    public boolean isSetTiming() {
        return true;
    }

    /**
     * Gets the value of the power property.
     * 
     */
    @Basic
    @Column(name = "power", scale = 0)
    public int getPower() {
        return power;
    }

    /**
     * Sets the value of the power property.
     * 
     */
    public void setPower(int value) {
        this.power = value;
    }

    @Transient
    public boolean isSetPower() {
        return true;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof BattingAttributes)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final BattingAttributes that = ((BattingAttributes) object);
        equalsBuilder.append(this.getObjectId(), that.getObjectId());
        equalsBuilder.append(this.getAbility(), that.getAbility());
        equalsBuilder.append(this.getTiming(), that.getTiming());
        equalsBuilder.append(this.getPower(), that.getPower());
    }

    public boolean equals(Object object) {
        if (!(object instanceof BattingAttributes)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getObjectId());
        hashCodeBuilder.append(this.getAbility());
        hashCodeBuilder.append(this.getTiming());
        hashCodeBuilder.append(this.getPower());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
