//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.01 at 02:50:57 PM GMT 
//


package com.siebentag.cj.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.siebentag.cj.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.siebentag.cj.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Wicket }
     * 
     */
    public Wicket createWicket() {
        return new Wicket();
    }

    /**
     * Create an instance of {@link BatsmanInningsCollection }
     * 
     */
    public BatsmanInningsCollection createBatsmanInningsCollection() {
        return new BatsmanInningsCollection();
    }

    /**
     * Create an instance of {@link Team }
     * 
     */
    public Team createTeam() {
        return new Team();
    }

    /**
     * Create an instance of {@link MatchInnings }
     * 
     */
    public MatchInnings createMatchInnings() {
        return new MatchInnings();
    }

    /**
     * Create an instance of {@link SeasonCollection }
     * 
     */
    public SeasonCollection createSeasonCollection() {
        return new SeasonCollection();
    }

    /**
     * Create an instance of {@link Match }
     * 
     */
    public Match createMatch() {
        return new Match();
    }

    /**
     * Create an instance of {@link Ball }
     * 
     */
    public Ball createBall() {
        return new Ball();
    }

    /**
     * Create an instance of {@link Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link Partnership }
     * 
     */
    public Partnership createPartnership() {
        return new Partnership();
    }

    /**
     * Create an instance of {@link BowlerInnings }
     * 
     */
    public BowlerInnings createBowlerInnings() {
        return new BowlerInnings();
    }

    /**
     * Create an instance of {@link PlayerCollection }
     * 
     */
    public PlayerCollection createPlayerCollection() {
        return new PlayerCollection();
    }

    /**
     * Create an instance of {@link BallCollection }
     * 
     */
    public BallCollection createBallCollection() {
        return new BallCollection();
    }

    /**
     * Create an instance of {@link Player }
     * 
     */
    public Player createPlayer() {
        return new Player();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link BattingAttributes }
     * 
     */
    public BattingAttributes createBattingAttributes() {
        return new BattingAttributes();
    }

    /**
     * Create an instance of {@link Competition }
     * 
     */
    public Competition createCompetition() {
        return new Competition();
    }

    /**
     * Create an instance of {@link Over }
     * 
     */
    public Over createOver() {
        return new Over();
    }

    /**
     * Create an instance of {@link OverCollection }
     * 
     */
    public OverCollection createOverCollection() {
        return new OverCollection();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link BowlerInningsCollection }
     * 
     */
    public BowlerInningsCollection createBowlerInningsCollection() {
        return new BowlerInningsCollection();
    }

    /**
     * Create an instance of {@link Season }
     * 
     */
    public Season createSeason() {
        return new Season();
    }

    /**
     * Create an instance of {@link BatsmanInnings }
     * 
     */
    public BatsmanInnings createBatsmanInnings() {
        return new BatsmanInnings();
    }

    /**
     * Create an instance of {@link Extra }
     * 
     */
    public Extra createExtra() {
        return new Extra();
    }

    /**
     * Create an instance of {@link MatchCollection }
     * 
     */
    public MatchCollection createMatchCollection() {
        return new MatchCollection();
    }

}
